apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-controller-manager
  labels:
    control-plane: camel-controller-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      control-plane: camel-controller-manager
  template:
    metadata:
      labels:
        control-plane: camel-controller-manager
    spec:
      serviceAccountName: camel-controller-manager
      containers:
        - name: manager
          image: gcr.io/knative-releases/github.com/knative/eventing-contrib/camel/source/cmd/controller@sha256:73765296e64b8d2e365132982475ca3a491a2c822b743a8cfa1a30b9d2d7550f
          imagePullPolicy: IfNotPresent

