apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: camel-controller-manager
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - sources.eventing.knative.dev
    resources:
      - camelsources
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - sources.eventing.knative.dev
    resources:
      - camelsources/status
      - camelsources/finalizers
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - camel.apache.org
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete